#!/usr/bin/env bash
#
# Make .tex file from .md
# -Uthpala Herath
#
# Usage:
# maketex infile.md outfile.tex

pandoc --natbib --filter pandoc-fignos --filter pandoc-eqnos --filter pandoc-tablenos --filter pandoc-secnos --number-sections -s $1 -o $2
